$pubKey = Get-Content "$env:USERPROFILE\.ssh\id_rsa.pub"
$password = "Jn4gix0mjDbb"
$sshHost = "45.136.14.88"
$port = "61709"
$user = "root"

Write-Host "请手动执行以下步骤来配置SSH密钥认证："
Write-Host ""
Write-Host "1. SSH连接到服务器："
Write-Host "   ssh root@45.136.14.88 -p 61709"
Write-Host "   密码: Jn4gix0mjDbb"
Write-Host ""
Write-Host "2. 执行以下命令："
Write-Host "   mkdir -p ~/.ssh"
Write-Host "   echo '$pubKey' >> ~/.ssh/authorized_keys"
Write-Host "   chmod 700 ~/.ssh"
Write-Host "   chmod 600 ~/.ssh/authorized_keys"
Write-Host ""
Write-Host "3. 退出SSH连接后，SSH MCP将能够使用密钥认证"
